from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
import json
import re
import warnings
import zipfile
import xml.etree.ElementTree as ET
from typing import Iterable

from .identifiers import iter_unlabeled_tax_identifiers


@dataclass(frozen=True)
class LeakFinding:
    kind: str
    location: str
    evidence: str


@dataclass
class LeakReport:
    findings: list[LeakFinding] = field(default_factory=list)
    requires_manual_visual_review: bool = False

    @property
    def automated_checks_passed(self) -> bool:
        return not self.findings

    @property
    def passed(self) -> bool:
        """Fail closed: visual derivatives are not publishable before manual review."""
        return not self.findings and not self.requires_manual_visual_review


# Deliberately conservative for public fixtures. False positives should force
# review rather than allow a private identifier through.
_BLOCKING_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("email", re.compile(r"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b")),
    ("url", re.compile(r"(?i)\b(?:https?://|www\.)\S+")),
    ("inn", re.compile(r"(?i)\bИНН\s*[:№]?\s*\d{10,12}\b")),
    ("kpp", re.compile(r"(?i)\bКПП\s*[:№]?\s*\d{9}\b")),
    ("ogrn", re.compile(r"(?i)\bОГРН(?:ИП)?\s*[:№]?\s*\d{13,15}\b")),
    ("bik", re.compile(r"(?i)\bБИК\s*[:№]?\s*\d{9}\b")),
    ("bank_account", re.compile(r"(?<!\d)\d{20}(?!\d)")),
    ("phone", re.compile(r"(?<!\d)(?:\+7|8)[\s()\-]*\d{3}[\s()\-]*\d{3}[\s\-]*\d{2}[\s\-]*\d{2}(?!\d)")),
)

# Stage 1P public XLSX files are generated by our narrow rebuild path. We do not
# need to tolerate arbitrary OOXML features in public evaluation fixtures: doing
# so would recreate the hidden-state problem that allowlist reconstruction is
# intended to remove.
_ALLOWED_PUBLIC_XLSX_MEMBERS = {
    "[content_types].xml",
    "_rels/.rels",
    "xl/_rels/workbook.xml.rels",
    "xl/workbook.xml",
    "xl/sharedstrings.xml",
    "xl/styles.xml",
    "xl/theme/theme1.xml",
    "docprops/core.xml",
    "docprops/app.xml",
}
_ALLOWED_PUBLIC_XLSX_SHEET_RE = re.compile(r"^xl/worksheets/sheet[1-9][0-9]*\.xml$")
_MAX_XLSX_MEMBERS = 128
_MAX_XLSX_MEMBER_BYTES = 10 * 1024 * 1024
_MAX_XLSX_UNCOMPRESSED_BYTES = 50 * 1024 * 1024
_MAX_JSON_BYTES = 5 * 1024 * 1024
_MAX_PUBLIC_IMAGE_PIXELS = 25_000_000


def _freeze_forbidden_tokens(forbidden_tokens: Iterable[str]) -> tuple[str, ...]:
    tokens = tuple(forbidden_tokens)
    if not all(isinstance(token, str) for token in tokens):
        raise TypeError("forbidden_tokens must contain strings only")
    return tokens


def scan_text(
    text: str,
    *,
    location: str = "text",
    forbidden_tokens: Iterable[str] = (),
    include_url: bool = True,
) -> list[LeakFinding]:
    findings: list[LeakFinding] = []
    for kind, pattern in _BLOCKING_PATTERNS:
        if kind == "url" and not include_url:
            continue
        if pattern.search(text):
            findings.append(LeakFinding(kind, location, f"matched {kind} pattern"))

    for kind in iter_unlabeled_tax_identifiers(text):
        findings.append(LeakFinding(kind, location, "matched checksum-valid unlabeled tax identifier"))

    folded = text.casefold()
    for token in forbidden_tokens:
        normalized = token.strip()
        if normalized and normalized.casefold() in folded:
            findings.append(LeakFinding("forbidden_token", location, "matched local denylist token"))
    return findings


def _scan_json(path: Path, forbidden_tokens: Iterable[str]) -> LeakReport:
    report = LeakReport()
    if path.stat().st_size > _MAX_JSON_BYTES:
        report.findings.append(LeakFinding("json_resource_limit", "json-file", "JSON file exceeds size limit"))
        return report
    try:
        raw = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        report.findings.append(LeakFinding("invalid_json_encoding", "json-file", "JSON is not valid UTF-8"))
        return report
    report.findings.extend(scan_text(raw, location="json-content", forbidden_tokens=forbidden_tokens))
    try:
        json.loads(raw)
    except json.JSONDecodeError as exc:
        report.findings.append(LeakFinding("invalid_json", "json-structure", f"parse error at line {exc.lineno}"))
    return report


def _public_xlsx_member_allowed(name: str) -> bool:
    lower = name.casefold()
    return lower in _ALLOWED_PUBLIC_XLSX_MEMBERS or bool(_ALLOWED_PUBLIC_XLSX_SHEET_RE.fullmatch(lower))


def _safe_xlsx_member_path(name: str) -> bool:
    if not name or "\\" in name or name.startswith("/"):
        return False
    path = PurePosixPath(name)
    return ".." not in path.parts and not path.is_absolute()


def _scan_xlsx(path: Path, forbidden_tokens: Iterable[str]) -> LeakReport:
    report = LeakReport()
    try:
        with zipfile.ZipFile(path) as archive:
            infos = archive.infolist()
            if len(infos) > _MAX_XLSX_MEMBERS:
                report.findings.append(
                    LeakFinding("xlsx_resource_limit", "xlsx-container", "too many XLSX container members")
                )
                return report

            names = [info.filename for info in infos]
            folded_names = [name.casefold() for name in names]
            if len(folded_names) != len(set(folded_names)):
                report.findings.append(
                    LeakFinding("xlsx_duplicate_member", "xlsx-container", "ambiguous duplicate XLSX member name present")
                )
                return report

            total_uncompressed = sum(info.file_size for info in infos)
            if total_uncompressed > _MAX_XLSX_UNCOMPRESSED_BYTES:
                report.findings.append(
                    LeakFinding("xlsx_resource_limit", "xlsx-container", "XLSX uncompressed size exceeds limit")
                )
                return report

            for index, info in enumerate(infos, start=1):
                name = info.filename
                location = f"xlsx-member-{index}"
                lower = name.casefold()

                if not _safe_xlsx_member_path(name):
                    report.findings.append(
                        LeakFinding("xlsx_unsafe_member_path", location, "unsafe XLSX member path")
                    )
                    continue
                if not _public_xlsx_member_allowed(name):
                    report.findings.append(
                        LeakFinding("xlsx_unapproved_part", location, "unapproved internal XLSX part")
                    )
                    continue
                if info.file_size > _MAX_XLSX_MEMBER_BYTES:
                    report.findings.append(
                        LeakFinding("xlsx_resource_limit", location, "XLSX member exceeds size limit")
                    )
                    continue
                if info.flag_bits & 0x1:
                    report.findings.append(
                        LeakFinding("xlsx_encrypted_part", location, "encrypted XLSX member is not inspectable")
                    )
                    continue

                report.findings.extend(scan_text(name, location=location, forbidden_tokens=forbidden_tokens))
                if lower.endswith((".xml", ".rels")):
                    try:
                        data = archive.read(info)
                    except (RuntimeError, zipfile.BadZipFile):
                        report.findings.append(
                            LeakFinding("invalid_xlsx_member", location, "XLSX member could not be inspected")
                        )
                        continue
                    try:
                        root = ET.fromstring(data)
                    except ET.ParseError:
                        report.findings.append(LeakFinding("invalid_xlsx_xml", location, "unparseable XML part"))
                        continue
                    for elem in root.iter():
                        if elem.text:
                            report.findings.extend(
                                scan_text(elem.text, location=location, forbidden_tokens=forbidden_tokens)
                            )
                        if elem.tail:
                            report.findings.extend(
                                scan_text(elem.tail, location=location, forbidden_tokens=forbidden_tokens)
                            )
                        attrs = {k.rsplit("}", 1)[-1]: str(v) for k, v in elem.attrib.items()}
                        if attrs.get("TargetMode", "").casefold() == "external":
                            report.findings.append(
                                LeakFinding("external_relationship", location, "external relationship present")
                            )
                            report.findings.extend(
                                scan_text(
                                    attrs.get("Target", ""),
                                    location=location,
                                    forbidden_tokens=forbidden_tokens,
                                )
                            )
                        for attr_name, attr_value in attrs.items():
                            if attr_name in {"Type", "Target", "TargetMode"}:
                                continue
                            report.findings.extend(
                                scan_text(
                                    attr_value,
                                    location=location,
                                    forbidden_tokens=forbidden_tokens,
                                    include_url=False,
                                )
                            )
    except zipfile.BadZipFile:
        report.findings.append(LeakFinding("invalid_xlsx", "xlsx-container", "not a valid XLSX/ZIP container"))
    return report


def _scan_image(path: Path, forbidden_tokens: Iterable[str]) -> LeakReport:
    from PIL import Image, UnidentifiedImageError

    report = LeakReport(requires_manual_visual_review=True)
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            with Image.open(path) as image:
                if image.width * image.height > _MAX_PUBLIC_IMAGE_PIXELS:
                    report.findings.append(
                        LeakFinding("image_resource_limit", "image-container", "image exceeds Stage 1P pixel limit")
                    )
                    return report
                if getattr(image, "n_frames", 1) != 1:
                    report.findings.append(
                        LeakFinding("image_multiframe", "image-container", "visual derivative must contain one frame")
                    )
                expected_format = "PNG" if path.suffix.lower() == ".png" else "JPEG"
                if image.format != expected_format:
                    report.findings.append(
                        LeakFinding("image_format_mismatch", "image-container", "image encoding does not match filename")
                    )
                exif = image.getexif()
                if exif and len(exif):
                    report.findings.append(
                        LeakFinding("image_exif_present", "image-metadata", "EXIF metadata present")
                    )
                    for value in exif.values():
                        if isinstance(value, str):
                            report.findings.extend(
                                scan_text(value, location="image-metadata", forbidden_tokens=forbidden_tokens)
                            )
                # Stage 1P visual derivatives are intended to be pixel-only.
                # Any auxiliary image info (including ICC/XMP/text chunks) is blocking.
                for value in image.info.values():
                    if value not in (None, "", b""):
                        report.findings.append(
                            LeakFinding("image_metadata_present", "image-metadata", "auxiliary image metadata present")
                        )
                        if isinstance(value, str):
                            report.findings.extend(
                                scan_text(value, location="image-metadata", forbidden_tokens=forbidden_tokens)
                            )
                        elif isinstance(value, bytes):
                            decoded = value.decode("utf-8", errors="ignore")
                            if decoded:
                                report.findings.extend(
                                    scan_text(decoded, location="image-metadata", forbidden_tokens=forbidden_tokens)
                                )
    except (Image.DecompressionBombWarning, Image.DecompressionBombError):
        report.findings.append(
            LeakFinding("image_resource_limit", "image-container", "image exceeds safe decode limits")
        )
    except (UnidentifiedImageError, OSError):
        report.findings.append(LeakFinding("invalid_image", "image-container", "image could not be inspected"))
    return report


def scan_path(path: str | Path, *, forbidden_tokens: Iterable[str]) -> LeakReport:
    tokens = _freeze_forbidden_tokens(forbidden_tokens)
    p = Path(path)
    if not p.is_file():
        return LeakReport(findings=[LeakFinding("missing_file", "file", "path is not a regular file")])

    filename_findings = scan_text(p.name, location="filename", forbidden_tokens=tokens)
    suffix = p.suffix.lower()
    if suffix == ".json":
        report = _scan_json(p, tokens)
    elif suffix == ".xlsx":
        report = _scan_xlsx(p, tokens)
    elif suffix in {".png", ".jpg", ".jpeg"}:
        report = _scan_image(p, tokens)
    else:
        report = LeakReport()
        report.findings.append(
            LeakFinding("unsupported_format", "file", f"unsupported public derivative format: {suffix}")
        )

    report.findings[:0] = filename_findings
    return report
